In [1]:
import csv, re
import pandas as pd

re_word = re.compile(r'창원시 (.*구)내에서')

data = {
    '지역': [],
    '2017': [],
    '2018': [],
    '2019': []
}

with open('changwon_link.csv') as f:
    cells = csv.DictReader(f)

    for k in cells:
        index = -1
        region = re_word.search(k['시도명']).group(1)

        if region in data['지역']:
            index = data['지역'].index(region)
        else:
            data['지역'].append(region)
            data['2017'].append(0)
            data['2018'].append(0)
            data['2019'].append(0)

        if '2017' in k['년도']:
            data['2017'][index] += int(k['총사고건수'])
        elif '2018' in k['년도']:
            data['2018'][index] += int(k['총사고건수'])
        elif '2019' in k['년도']:
            data['2019'][index] += int(k['총사고건수'])

result = pd.DataFrame(data)
result

      지역  2017  2018  2019
0    의창구    43    47    40
1    성산구    64    55    83
2  마산합포구    76    71    88
3  마산회원구    12    33    28
4    진해구    65    26    49